name: Feature Request
description: Suggest a new feature or enhancement for Unity agents
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your request.

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of feature request is this?
      options:
        - New Unity agent
        - Enhancement to existing agent
        - New documentation
        - Workflow improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Related Agent (if applicable)
      description: Which agent would this feature relate to?
      options:
        - unity-game-architect
        - unity-gameplay-programmer  
        - unity-physics-engineer
        - unity-animation-specialist
        - unity-ui-ux-designer
        - unity-rendering-engineer
        - unity-performance-optimizer
        - unity-network-programmer
        - unity-audio-engineer
        - unity-qa-engineer
        - unity-analytics-engineer
        - unity-tools-programmer
        - unity-monetization-specialist
        - unity-localization-specialist
        - unity-accessibility-specialist
        - unity-shader-programmer
        - unity-data-engineer
        - unity-security-engineer
        - unity-console-developer
        - unity-web-developer
        - unity-cloud-engineer
        - New agent needed
        - Not applicable

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case are you trying to address?
      placeholder: "Currently, when working with Unity, developers struggle with..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like to see an agent that can..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternatives have you considered?
      placeholder: "I've considered using existing tools like... but they don't meet the need because..."

  - type: textarea
    id: examples
    attributes:
      label: Example Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. When creating a 2D platformer game...
        2. For mobile game optimization...
        3. In multiplayer game development...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to your workflow?
      options:
        - Low - Nice to have
        - Medium - Would improve productivity
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor addition or modification
        - Medium - Moderate development effort
        - Complex - Significant development required
        - Not sure

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: "Links to documentation, similar implementations, or specific requirements..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature once implemented
        - label: I would be willing to provide documentation for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: I have considered how this fits into the existing agent ecosystem
          required: true